---
title: "correlations_and_distributions"
author: "Léo Gorman"
date: '2023-01-11'
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, echo=F}
# knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/lgorman/research/phd/farm-size-modelling/')

library(readr)
library(dplyr)
library(tibble)
library(jsonlite)
library(tidyr)

# Spatial Packages
library(sf)
library(sp)
library(stars)
library(geojsonsf)
library(corrplot)
library(raster)
library(leaflet)
library(mapview)

# Graph Plotting
library(ggplot2)
# library(ggridges)
library(ggExtra)
library(RColorBrewer)
library(GGally)

# library(moments) # Package for skewness
library(gamlss) # Gaussian additive models for location, scale, and shape
# library(bamlss) # Bayesian additive models for location, scale, and shape
library(brms) # General package for bayesian models with lme4 syntax and stan backend
library(lme4) # General package for bayesian multi-level modelling.
library(FactoMineR) # Package for pca
library(factoextra) # Extra pca features

library(fitdistrplus)


```

## Loading Data



```{r , message=F, warning=F}
indicator_data <- readr::read_csv("./data/prepped-data/rhomis-ee-gaez.csv")
indicator_data <- indicator_data[!is.na(indicator_data$gps_lat) & !is.na(indicator_data$gps_lon),]
indicator_data_geo <- st_as_sf(indicator_data, coords = c("gps_lon", "gps_lat"), 
                               crs = 4326, agr = "constant", remove = F)



# FAO administrative data
fao_level_2 <- geojson_sf('data/prepped-data/fao_level_2.geojson')
fao_level_2 <- sf::st_as_sf(x = fao_level_2, wkt = "geometry")
fao_level_2_geo <-st_set_crs(fao_level_2,'EPSG:4326')

fao_level_2 <- tibble::as_tibble(fao_level_2)

land_categories <-  readr::read_csv("./data/prepped-data/land_cover_classes.csv")
```


## Cleaning

```{r , message=F, warning=F}
indicator_data <- indicator_data[!is.na(indicator_data$land_cultivated_ha),]
indicator_data <- indicator_data[!is.na(indicator_data$AEZ_Classes_33),]

land_cat_columns <- paste0("land_cat_",c(1:17))
indicator_data[land_cat_columns] <- lapply(indicator_data[land_cat_columns] , function(column){
  column[is.na(column)] <- 0
  # Dividing the number of pixels by total pixel count for that area
  column <- column/indicator_data$pixelCount
  return(column)
}) %>% dplyr::bind_cols()

fao_level_2[land_cat_columns] <- lapply(fao_level_2[land_cat_columns] , function(column){
  column <- as.numeric(column)
  column[is.na(column)] <- 0
  # Dividing the number of pixels by total pixel count for that area
  column <- column/fao_level_2$pixelCount
  return(column)
}) %>% dplyr::bind_cols()


new_land_cat_columns <- land_categories$Tag
colnames(indicator_data)[colnames(indicator_data) %in% land_cat_columns] <- new_land_cat_columns
colnames(fao_level_2)[colnames(fao_level_2) %in% land_cat_columns] <- new_land_cat_columns

colnames(indicator_data)[colnames(indicator_data) == "accessibility_mean"] <-"healthcare_traveltime"
colnames(indicator_data)[colnames(indicator_data) == "b1_mean_mean"] <- "nightlights"
colnames(indicator_data)[colnames(indicator_data) == "population_density_mean_mean"] <- "population_density"

colnames(indicator_data)[colnames(indicator_data) == "elevation_mean"] <- "elevation"
colnames(indicator_data)[colnames(indicator_data) == "NDVI_mean_mean"] <- "ndvi"
colnames(indicator_data)[colnames(indicator_data) == "constant_mean"] <- "topographic_diversity"

colnames(fao_level_2)[colnames(fao_level_2) == "accessibility_mean"] <-"healthcare_traveltime"
colnames(fao_level_2)[colnames(fao_level_2) == "b1_mean_mean"] <- "nightlights"
colnames(fao_level_2)[colnames(fao_level_2) == "population_density_mean_mean"] <- "population_density"

colnames(fao_level_2)[colnames(fao_level_2) == "elevation_mean"] <- "elevation"
colnames(fao_level_2)[colnames(fao_level_2) == "NDVI_mean_mean"] <- "ndvi"
colnames(fao_level_2)[colnames(fao_level_2) == "constant_mean"] <- "topographic_diversity"

indicator_data$geo_id <- paste0(indicator_data$ADM0_CODE, "_", 
                                indicator_data$ADM1_CODE, "_",
                                indicator_data$ADM2_CODE)

fao_level_2$geo_id <- paste0(fao_level_2$ADM0_CODE, "_", 
                             fao_level_2$ADM1_CODE, "_",
                             fao_level_2$ADM2_CODE)


```


## Outlier Detection

```{r, message=F, warning=F}

outlier_filter <- quantile(indicator_data[["land_cultivated_ha"]], probs = c(0.01,0.99))

table(indicator_data[c("land_cultivated_ha")]==outlier_filter[1]) # 236 with 0 land cult (investigate further)
table(indicator_data[c("land_cultivated_ha")]>outlier_filter[2]) # 201 with land cult greater than 99th percentile (24th)


indicator_data <- indicator_data[indicator_data[c("land_cultivated_ha")] != outlier_filter[1] & indicator_data[c("land_cultivated_ha")] <= outlier_filter[2],]





```
## Variable Distributions
```{r  message=F, warning=F}

counts_per_area <- as.data.frame(table(indicator_data$geo_id))
colnames(counts_per_area) <- c('geo_id', "Freq")
ggplot(counts_per_area, aes(x=Freq))+
  geom_histogram()



```

```{r  message=F, warning=F}

counts_per_area <- as.data.frame(table(indicator_data$geo_id))
colnames(counts_per_area) <- c('geo_id', "Freq")
ggplot(counts_per_area, aes(x=Freq))+
  geom_histogram()+
  xlim(0,100)



```

## Prioritisation

```{r}

summarised_land_size <- indicator_data %>% 
  group_by(geo_id)%>%  
  summarise(
    mean= mean(land_cultivated_ha, na.rm=T),
    median = median(land_cultivated_ha, na.rm=T),
    q_0.1 = quantile(land_cultivated_ha,probs=c(0.1), na.rm=T),
    n=n()
  )

ggplot(summarised_land_size, aes(x=mean, y=q_0.1, size=n))+
  geom_point()

summarised_land_size$order_q1 <- order(summarised_land_size$q_0.1)
summarised_land_size$log_q_0.1 <- log(summarised_land_size$q_0.1)

summarised_land_size$order_mean <- order(summarised_land_size$mean)
summarised_land_size$order_median <- order(summarised_land_size$median)

ggplot(summarised_land_size, aes(x=order_mean, y=order_q1, size=n))+
  geom_point()
ggplot(summarised_land_size, aes(x=order_median, y=order_q1, size=n))+
  geom_point()


ggplot(summarised_land_size,aes(x=mean))+
  geom_histogram()

ggplot(summarised_land_size,aes(x=q_0.1))+
  geom_histogram()

ggplot(summarised_land_size,aes(x=log_q_0.1))+
  geom_histogram()



plotdist(summarised_land_size$q_0.1, histo = TRUE, demp = TRUE)
plotdist(summarised_land_size$mean, histo = TRUE, demp = TRUE)

descdist(summarised_land_size$q_0.1, boot = 1000)
descdist(summarised_land_size$mean, boot = 1000)


fit_dist_0.1 <- fitdist(as.numeric(summarised_land_size$q_0.1), "weibull")
fit_dist_mean <- fitdist(as.numeric(summarised_land_size$mean), "weibull")

denscomp(list(fit_dist_0.1))
qqcomp(list(fit_dist_0.1))
cdfcomp(list(fit_dist_0.1))
ppcomp(list(fit_dist_0.1))

gofstat(fit_dist_0.1)

boot_fit <- bootdist(fit_dist_0.1, niter = 1001)
summary(boot_fit)
plot(boot_fit)

summarised_land_size$p_q_0.1 <- pweibull(as.numeric(summarised_land_size$q_0.1),
                                         fit_dist_0.1$estimate["shape"], 
                                         fit_dist_0.1$estimate["scale"])

summarised_land_size$p_mean <- pweibull(summarised_land_size$mean,
                                        fit_dist_mean$estimate["shape"], 
                                        fit_dist_mean$estimate["scale"])



allocation_weights_q_0.1 <- 1-summarised_land_size$p_q_0.1
allocation_weights_q_0.1 <- allocation_weights_q_0.1/sum(allocation_weight_q_0.1)

allocation_weights_mean <-1-summarised_land_size$p_mean
allocation_weights_mean <- allocation_weights_mean/sum(allocation_weights_mean)

summarised_land_size$allocation_weights_q_0.1 <- allocation_weights_q_0.1
summarised_land_size$allocation_weights_mean <- allocation_weights_mean



ggplot(summarised_land_size, aes(x=allocation_weights_mean, y=allocation_weights_q_0.1))+ geom_point()+
  geom_abline(intercept = 0, slope = 1)+   
  
  
  
  
  
  
  
  ```



## Correlation Data Prep
```{r  message=F, warning=F}
x <- c("healthcare_traveltime",
       "nightlights",
       "population_density",
       
       
       "elevation",
       "ndvi",
       "topographic_diversity",
       "adjusted_length_growing_period",
       
       
       
       new_land_cat_columns
)

aez_33 <- grep("AEZ_Classes_33_", colnames(indicator_data), value=T)




y <-c("land_cultivated_ha")


# Looking at subnational indicators vas land cultivated
# cor(indicator_data[c(x,aez_33,y)])

corr_matrix <- round(cor(indicator_data[c(x,aez_33,y)]),2) %>% tibble::as_tibble()
corr_matrix$var <- colnames(corr_matrix)
corr_matrix <- corr_matrix %>% pivot_longer(cols = colnames(corr_matrix)[colnames(corr_matrix)!="var"])

colnames(corr_matrix) <- c("var1", "var2", "value")


land_cult_corr <- corr_matrix[corr_matrix$var1=="land_cultivated_ha", ]
land_cult_corr <- land_cult_corr[land_cult_corr$var2!="land_cultivated_ha",]

land_cult_corr$var2 <- gsub("AEZ_Classes_33_", "",land_cult_corr$var2)

land_cult_corr$var2 <- factor(land_cult_corr$var2, levels=c(x,gsub("AEZ_Classes_33_", "",aez_33)), ordered = T)
land_cult_corr$factor_level <- as.numeric(land_cult_corr$var2)

socio_economic <- c("healthcare_traveltime",
                    "nightlights",
                    "population_density")

environmental <- c("elevation",
                   "ndvi",
                   "topographic_diversity",
                   "adjusted_length_growing_period")



land_cat <- new_land_cat_columns

land_cult_corr$var_group <- NA
land_cult_corr$var_group[land_cult_corr$var2 %in% socio_economic] <- "Socio-Economic"
land_cult_corr$var_group[land_cult_corr$var2 %in% environmental] <- "Environmental"
land_cult_corr$var_group[land_cult_corr$var2 %in% land_cat] <- "Land-Cover-Class"
land_cult_corr$var_group[land_cult_corr$var2 %in% gsub("AEZ_Classes_33_", "",aez_33)] <- "Agro-Eco-Zone"

land_cult_corr$var_group <- factor(land_cult_corr$var_group, 
                                   levels=c("Agro-Eco-Zone",
                                            "Land-Cover-Class",
                                            "Environmental",
                                            "Socio-Economic"),
                                   ordered=T, )

land_cult_corr <- land_cult_corr[!is.na(land_cult_corr$value),]



```





## Variable Distributions

### Variance

```{r cars, message=F, warning=F}
gathered_data <- indicator_data[c(x,aez_33,y)] %>% gather()


summary_gathered <-gathered_data %>% group_by(key) %>% 
  summarise(
    mean= mean(value, na.rm=T),
    sd= sd(value, na.rm=T)
    
  )

values_to_remove <- summary_gathered$key[summary_gathered$mean==0 & summary_gathered$sd==0]

values_to_keep <- summary_gathered$key[summary_gathered$mean!=0 | summary_gathered$sd!=0]




```


```{r  message=F, warning=F}
gathered_data <- gathered_data[gathered_data$key==values_to_keep,]
gathered_data$key <- gsub("AEZ_Classes_33", "",gathered_data$key)
ggplot(gathered_data, aes(x=value))+ 
  geom_histogram()+
  facet_wrap(~ key, scales = "free") 




```

